config/routes.rb
VirtusKnowledge::Application.routes.draw do

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  get "indicators/show"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/research_groups/:id/programs" => "research_groups#programs"
  match "/research_groups/:id/projects" => "research_groups#projects"
  match "/research_groups/:id/results" => "research_groups#results"

  match "/research_lines/:id/programs" => "research_lines#programs"
  match "/research_lines/:id/projects" => "research_lines#projects"
  match "/research_lines/:id/results" => "research_lines#results"
  match "/research_lines/:id/entries" => "research_lines#entries"
  match "/research_lines/:id/research_sublines" => "research_lines#research_sublines"

  match "/research_sublines/:id/programs" => "research_sublines#programs"
  match "/research_sublines/:id/projects" => "research_sublines#projects"
  match "/research_sublines/:id/results" => "research_sublines#results"
  match "/research_sublines/:id/entries" => "research_sublines#entries"

  match "/knowledge_areas/:id/programs" => "knowledge_areas#programs"
  match "/knowledge_areas/:id/projects" => "knowledge_areas#projects"
  match "/knowledge_areas/:id/results" => "knowledge_areas#results"
  match "/knowledge_areas/:id/entries" => "knowledge_areas#entries"

  match "/departments/:id/knowledge_areas" => "departments#knowledge_areas"
  match "/departments/:id/programs" => "departments#programs"
  match "/departments/:id/projects" => "departments#projects"
  match "/departments/:id/results" => "departments#results"
  match "/departments/:id/entries" => "departments#entries"

  match "/users/:id/programs" => "users#programs"
  match "/users/:id/projects" => "users#projects"
  match "/users/:id/results" => "users#results"
  match "/users/:id/entries" => "users#entries"
  match "/users/:id/groups_programs" => "users#groups_programs"
  match "/users/:id/groups_projects" => "users#groups_projects"
  match "/my_groups_programs" => "users#my_groups_programs", :as => "my_groups_programs"
  match "/my_groups_projects" => "users#my_groups_projects", :as => "my_groups_projects"

  match "/programs/type/:id" => "programs#program_type"

  match "/research_groups/:object_id/type/:type_id" => "research_groups#program_type"
  match "/departments/:object_id/type/:type_id" => "departments#program_type"
  match "/users/:object_id/type/:type_id" => "users#program_type"

  match "search/:search" => "pages#search"
  match "search/" => "pages#search", :as => "search_general"

  get "departments/search/:search" => "departments#search"
  get "knowledge_areas/search/:search" => "knowledge_areas#search"
  get "research_lines/search/:search" => "research_lines#search"
  get "research_sublines/search/:search" => "research_sublines#search"
  get "programs/search/:search" => "programs#search"
  get "projects/search/:search" => "projects#search"
  get "results/search/:search" => "results#search"
  get "entries/search/:search" => "entries#search"
  get "users/search/:search" => "users#search"

  get "bydepartment" => "pages#bydepartment"

  match "/users/:id/all" => "users#show"

  get "timeline" => "pages#timeline", :as => "timeline"

  get "departments/show"

  get "departments/index"

  get "help" => "pages#help", :as => "help"

  get "about" => "pages#about", :as => "about"

  get "explore" => "pages#explore", :as => "explore"

  get "myaccount" => 'users#myaccount', :as => "myaccount"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get "signup" => "users#new", :as => "signup"

  resources :password_resets

  resources :users  do
    member do
      get :activate
    end
  end
  resources :sessions
  resources :entries
  resources :research_lines
  resources :research_sublines
  resources :knowledge_areas
  resources :departments
  resources :programs do
    resources :indicators
  end
  resources :projects
  resources :results
  resources :research_groups

  get "myentries" => "entries#myentries", :as => "myentries"

  get "myprograms" => "programs#myprograms", :as => "myprograms"
  get "myprojects" => "projects#myprojects", :as => "myprojects"
  get "myresults" => "results#myresults", :as => "myresults"
  get "mygroups" => "research_groups#mygroups", :as => "mygroups"

  root :to => 'pages#home'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :user
  belongs_to :program
	validates :title, :presence => true
  validates :program_id, :presence => true

	self.per_page = 5
	#after_initialize :default_values

  has_many :documents, :dependent => :destroy
  attr_accessible :documents_attributes

  accepts_nested_attributes_for :documents, :reject_if => lambda { |a| a[:file].blank? }, :allow_destroy => true

	has_many :images, :dependent => :destroy
	accepts_nested_attributes_for :images, :reject_if => lambda { |a| a[:image].blank? }, :allow_destroy => true
	attr_accessible :images_attributes, :title, :body, :date, :published, :program_id
	
	has_and_belongs_to_many :research_sublines

	attr_reader :research_subline_names
	attr_accessible :research_subline_names

  def research_subline_names=(names)
  	research_sublines = Array.new
    knowledge_areas = Array.new
  	for name in names 
  		research_subline = ResearchSubline.find_by_name(name)
      unless research_subline.nil?
        research_sublines.push(research_subline)
        unless research_subline.knowledge_area.nil?
          knowledge_areas.push(research_subline.knowledge_area)
        end
      end
  	end
    self.research_sublines = research_sublines
    self.knowledge_areas = knowledge_areas
  end



  has_and_belongs_to_many :knowledge_areas

  attr_reader :knowledge_area_names
  attr_accessible :knowledge_area_names

  def knowledge_area_names=(names)
    knowledge_areas = Array.new
    for name in names
      knowledge_area = KnowledgeArea.find_by_name(name)
      knowledge_areas.push(knowledge_area)
    end
    self.knowledge_areas = knowledge_areas
  end

	def owned_by?(owner)
		return false unless owner.is_a? User
		user == owner
	end

	def author
		user.name
  end

  def self.search(query)
    where do
      (title =~ "%#{query}%") | (body =~ "%#{query}%")
    end
  end

	#private
	#	def default_values
	#		self.date ||= Time.now.strftime("%Y-%m-%d")
   #   self.published = true
	#	end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :require_login, :only => [:new, :edit, :create, :update, :destroy, :myentries]
  before_filter :is_owner?, :only => [:edit, :update, :destroy, :show]
  def is_owner?
    entry = Entry.find(params[:id])
    unless current_user.nil?
      unless entry.owned_by?(current_user)
        unless entry.published
          redirect_to root_path
        end
      end
    else
      unless entry.published
        redirect_to root_path, :notice => t('application.please_sign_in')
      end
    end
  end

  def myentries
    @entries = current_user.entries.paginate(:page => params[:page]).order('date DESC')

    if @entries.empty?
      respond_to do |format|
        format.html { render :template => 'pages/myempty', :locals => { :model => Entry } }
      end
    else
      respond_to do |format|
        format.html { render :template => 'entries/index' }
        format.json { render json: @entries }
        format.js { render :template => 'entries/index' }
      end
    end
  end

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.where(:published => true).paginate(:page => params[:page]).order('date DESC')

    if @entries.empty?
      respond_to do |format|
        format.html { render :template => 'pages/empty' }
      end
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @entries }
        format.js
      end
    end

  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # timeline.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new
    @entry.images.build
    @entry.documents.build
    @programs = current_user.programs

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = current_user.entries.find(params[:id])
    @programs = current_user.programs
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = current_user.entries.new(params[:entry])

    respond_to do |format|
      if @entry.save
        session[:mixpanel] = "mixpanel.track('crear actividad');"
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = current_user.entries.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = current_user.entries.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :ok }
    end
  end

  def search
    @entries = Entry.search(params[:search]).paginate(:page => params[:page])
    @collection = @entries
    respond_to do |format|
      format.html { render :template => 'pages/search' }
      format.js { render :template => 'pages/search' }
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def just_created_or_updated
  	if uri?(request.referer)
	    if URI(request.referer).path == '/entries/new' || URI(request.referer).path.match(/\/entries\/[0-9]+\/edit/i)
	      true
	    else
	      false
	    end
    end
  end

  def uri?(string)
    uri = URI.parse(string)
    %w( http https ).include?(uri.scheme)
  rescue URI::BadURIError
    false
  rescue URI::InvalidURIError
    false
  end

end

app/views/entries/_entry.html.erb
<%= content_tag_for(:li, entry, :class => "entry") do %>
  <div class="row">
    <div class="span2">
      <% if entry.owned_by? current_user %>
      <span class="label label-<%= entry.published ? 'info' : 'warning' %>"><%= entry.published ? t('entry.published') : t('entry.not_published') %></span>
      <% end %>
      <%= link_to entry_path(entry), :class => 'thumbnail' do %>
        <% if entry.images.count > 0 %>
          <%= image_tag entry.images.first.image_url(:thumb) if entry.images.count > 0 && entry.images.first.image? %>
        <% else %>
          <img src="http://www.placehold.it/160x155/EFEFEF/AAAAAA&amp;text=no+image">
        <% end %>
      <% end %>
    </div>
    <div class="span6">
      <%= link_to entry_path(entry) do %>
        <h2><%= entry.title %></h2>
      <% end %>
      <% if entry.owned_by? current_user %>
      <div class="entry-actions pull-right">
      <%= link_to edit_entry_path(entry), :class => 'btn btn-mini btn-success' do %>
        <i class="icon-pencil icon-white"></i> <%= t('.edit', :default => t("helpers.links.edit")) %>
      <% end %>
      <%= link_to entry_path(entry),
                :method => :delete,
                :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                :class => 'btn btn-mini btn-danger' do %>
        <i class="icon-remove icon-white"></i> <%= t('.destroy', :default => t("helpers.links.destroy")) %>
      <% end %>
      </div>
      <% end %>
      <h3><%= link_to entry.author, user_path(entry.user.id) %> <% unless entry.date.nil? %><small><%= l entry.date, :format => :long %></small><% end %></h3>
      <% unless entry.body.blank? %>
        <%= truncate_html strip_tags(entry.body).gsub("&nbsp;", ""), :length => 250 %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/entries/_form.html.erb
<%= tinymce_assets %>
<%= simple_nested_form_for @entry, :validate => true, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @entry.errors.any? %>
  <div class="alert">
    <button class="close" data-dismiss="alert">x</button>
    <strong><%= t('application.warning') %></strong> <%= t('entry.could_not_create', :count => @entry.errors.count) %>
  </div>
  <% end %>

  <%= f.input :title, :input_html => { :class => 'span7' } %>
  <%= f.association :program, :collection => @programs, :input_html => { :class => 'span7' } %>
  <%= f.input :date, :as => :string, :input_html => { :class => 'span7' } %>

  <div class="entry-images controls span7">
    <%= f.fields_for :documents do |document_form| %>
      <div class="well">
        <h4><%= t("activerecord.models.document.one") %></h4>
        <%= document_form.input :name %>
        <%= document_form.input :file, :label => false %>

        <div class="control-group">
          <div class="controls">
            <%= document_form.link_to_remove t("application.remove_document") %>
          </div>
        </div>
      </div>
    <% end %>
    <%= f.link_to_add t("application.add_document"), :documents, :class => "add-image-link" %>
  </div>


  <div class="control-group">
    <label class="control-label"><%= t('entry.research_sublines') %></label>
    <div class="controls">
      <%= content_tag :ul, :class => "span7", :id => "research-sublines", data: {autocomplete_source: ResearchSubline.order(:name).map(&:name)}  do %>
        <% for research_subline in @entry.research_sublines %>
          <li><%= research_subline.name %></li>
        <% end %>
      <% end %>
    </div>
  </div>


  <%= f.input :published %>

  <div class="entry-images controls span7">
    <%= f.fields_for :images do |image_form| %>
      <div class="well">
        <h4><%= t("images.image") %></h4>
        <%= image_form.input :title %>
        
        <div class="control-group">
          <div class="controls">
            <div class="fileupload fileupload-new" data-fileupload="image"><input type="hidden">
              <div class="fileupload-new thumbnail" style="max-width: 200px; max-height: 150px;">
                <img src="<%= (image_form.object.image_url.present?)? image_form.object.image_url : "http://www.placehold.it/200x150/EFEFEF/&text=no+image"  %>">
              </div>
              <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 0px; "></div>
              <div>
                <span class="btn btn-file">
                  <span class="fileupload-new"><%= t('images.select_image') %></span>
                  <span class="fileupload-exists"><%= t('images.change_image') %></span>
                  <%= image_form.input_field :image %>
                </span>
                <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
              </div>
            </div>
          </div>
        </div>
        
        <div class="control-group">
          <div class="controls">
            <%= image_form.link_to_remove t("images.remove_image") %>
          </div>
        </div>
      </div>
    <% end %>
    <%= f.link_to_add t("images.add_image"), :images, :class => "add-image-link" %>
  </div>

  <%= f.input :body, :input_html => { :class => 'tinymce span7' } %>
  <%= tinymce %>

  <div class="form-actions">
    <div class="pull-right">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  entries_path, :class => 'btn' %>
    </div>
  </div>
<% end %>

app/views/entries/_sidebar.html.erb
<div class="well sidebar-nav">
  <%= render_navigation(:expand_all => true) %>
</div>

app/views/entries/_similar_sidebar.html.erb
<div class="well sidebar-nav">
  <%= render_navigation(:context => :similar, :expand_all => true) %>
</div>

app/views/entries/edit.html.erb
<div class="span9" id="entry-form">
  <div class="well">
	<%- model_class = @entry.class -%>
	<div class="page-header">
	  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
	                                   :default => "Editar #{model_class.model_name.human}") %></h1>
	</div>
	<%= render :partial => 'form' %>
  </div>
</div>

app/views/entries/index.html.erb
<%- model_class = Entry.new.class -%>
<div class="span8">
  <div class="well">
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human(:count => @entries.count )%></h1>
  </div>
  <ul class="thumbnails entries">
    <%= render @entries %>
  </ul>
  <div class="pull-right">
    <%= will_paginate @entries, :renderer => BootstrapPagination::Rails %>
  </div>
  </div>
</div>
<div class="span4">
  <%= render "entries/sidebar" %>
</div>

app/views/entries/index.js.erb
$('.entries').append('<%= j render(@entries) %>');
<% if @entries.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@entries, :renderer => BootstrapPagination::Rails) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/entries/new.html.erb
<div class="span9" id="entry-form">
  <div class="well">
	<%- model_class = @entry.class -%>
	<div class="page-header">
	  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
	                                 :default => "Nueva #{model_class.model_name.human}") %></h1>
	</div>
	<%= render :partial => 'form' %>
  </div>
</div>

app/views/entries/show.html.erb
<%- model_class = @entry.class -%>
<div class="span8 entry">
  <div class="well">
  <div class="page-header">
    <h1><%= @entry.title %></h1>
    <div class="entry-actions">
      <%= link_to just_created_or_updated ? myentries_path : :back, :class => 'btn btn-mini' do %>
        <i class="icon-white icon-arrow-left"></i> <%= t('.back', :default => t("helpers.links.back")) %>
      <% end %>
      <% if @entry.owned_by? current_user %>
        <%= link_to edit_entry_path(@entry), :class => 'btn btn-mini btn-success' do %>
          <i class="icon-pencil icon-white"></i> <%= t('.edit', :default => t("helpers.links.edit")) %>
        <% end %>
        <%= link_to entry_path(@entry),
                    :method => 'delete',
                    :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                    :class => 'btn btn-danger btn-mini' do %>
          <i class="icon-remove icon-white"></i> <%= t('.destroy', :default => t("helpers.links.destroy")) %>
        <% end %>
      <% end %>
    </div>
  </div>
  <% unless @entry.images.empty? %>
  <ul class="thumbnails">
    <% for image in @entry.images %>
      <li class="<%= (@entry.images.index(image)==0 || @entry.images.index(image)==0) ? 'span4' : 'span2'  %>">
        <%= link_to image.image_url(:modal), :class => "thumbnail", :rel => "prettyPhoto[pp_gal]" do %>
          <span class="overlay"></span>
          <%= image_tag image.image_url(:medium), :alt => image.title if image.image? %>
        <% end %>
      </li>
    <% end %>
  </ul>
      <hr>
  <% end %>

    <div class="page-header">
      <div>
        <h3 class="author"><%= t("entry.author") %>:</h3>
        <h4 class="author"><%= link_to @entry.author, user_path(@entry.user) %></h4>
      </div>
      <% unless @entry.date.nil? %>
        <div>
          <h3 class="author"><%= t('activerecord.attributes.entry.date') %>:</h3>
          <h4 class="author"><%= @entry.date %></h4>
        </div>
      <% end %>
      <% unless @entry.program.nil? %>
        <div>
          <h3 class="author"><%= t("activerecord.models.program.one") %>:</h3>
          <h4 class="author"><%= link_to @entry.program.title, program_path(@entry.program) %></h4>
        </div>
      <% end %>

      <% unless @entry.knowledge_areas.empty? %>
        <h3><%= t("activerecord.models.department.other") %>:</h3>
        <h4>
          <ul>
            <% for knowledge_area in @entry.knowledge_areas %>
              <li>
                <%= link_to knowledge_area.department.name, department_path(knowledge_area.department.id) %> <small>(<%= link_to knowledge_area.name, knowledge_area_path(knowledge_area.id) %>)</small>
              </li>
            <% end %>
          </ul>
        </h4>
      <% end %>

      <% unless @entry.research_sublines.empty? %>
        <h3><%= t("activerecord.models.research_line.other") %>:</h3>
        <h4>
          <ul>
            <% for research_subline in @entry.research_sublines %>
              <li>
                <%= link_to research_subline.research_line.name, research_line_path(research_subline.research_line) %> <small>(<%= link_to research_subline.name, url_for(research_subline) %>)</small>
              </li>
            <% end %>
          </ul>
        </h4>
      <% end %>


      <% unless @entry.documents.nil? or @entry.documents.count == 0 %>
        <div>
          <% for document in @entry.documents %>
            <div>
              <span class="download"></span>
              <%
                 unless document.name.blank?
                   download_name = t('application.download_file') + " - " + document.name
                 else
                   download_name = t('application.download_file')
                 end
              %>
              <h3 class="author"><%= link_to download_name, document.file_url  %></h3>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>



    <% unless @entry.body.blank? %>
      <div class="page-header">
        <h3><%= t "application.description" %>: </h3>
      </div>

      <div class="content">
        <%= @entry.body.html_safe %>
      </div>
      <hr>
    <% end %>
  </div>
</div>

<div class="span4">
    <%= render 'sidebar' %>

</div>


<div class="span8">
  <div class="well">
  <div id="disqus_thread"></div>
  <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'tesisespe'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
  </div>
</div>