config/routes.rb
VirtusKnowledge::Application.routes.draw do

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  get "indicators/show"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/research_groups/:id/programs" => "research_groups#programs"
  match "/research_groups/:id/projects" => "research_groups#projects"
  match "/research_groups/:id/results" => "research_groups#results"

  match "/research_lines/:id/programs" => "research_lines#programs"
  match "/research_lines/:id/projects" => "research_lines#projects"
  match "/research_lines/:id/results" => "research_lines#results"
  match "/research_lines/:id/entries" => "research_lines#entries"
  match "/research_lines/:id/research_sublines" => "research_lines#research_sublines"

  match "/research_sublines/:id/programs" => "research_sublines#programs"
  match "/research_sublines/:id/projects" => "research_sublines#projects"
  match "/research_sublines/:id/results" => "research_sublines#results"
  match "/research_sublines/:id/entries" => "research_sublines#entries"

  match "/knowledge_areas/:id/programs" => "knowledge_areas#programs"
  match "/knowledge_areas/:id/projects" => "knowledge_areas#projects"
  match "/knowledge_areas/:id/results" => "knowledge_areas#results"
  match "/knowledge_areas/:id/entries" => "knowledge_areas#entries"

  match "/departments/:id/knowledge_areas" => "departments#knowledge_areas"
  match "/departments/:id/programs" => "departments#programs"
  match "/departments/:id/projects" => "departments#projects"
  match "/departments/:id/results" => "departments#results"
  match "/departments/:id/entries" => "departments#entries"

  match "/users/:id/programs" => "users#programs"
  match "/users/:id/projects" => "users#projects"
  match "/users/:id/results" => "users#results"
  match "/users/:id/entries" => "users#entries"
  match "/users/:id/groups_programs" => "users#groups_programs"
  match "/users/:id/groups_projects" => "users#groups_projects"
  match "/my_groups_programs" => "users#my_groups_programs", :as => "my_groups_programs"
  match "/my_groups_projects" => "users#my_groups_projects", :as => "my_groups_projects"

  match "/programs/type/:id" => "programs#program_type"

  match "/research_groups/:object_id/type/:type_id" => "research_groups#program_type"
  match "/departments/:object_id/type/:type_id" => "departments#program_type"
  match "/users/:object_id/type/:type_id" => "users#program_type"

  match "search/:search" => "pages#search"
  match "search/" => "pages#search", :as => "search_general"

  get "departments/search/:search" => "departments#search"
  get "knowledge_areas/search/:search" => "knowledge_areas#search"
  get "research_lines/search/:search" => "research_lines#search"
  get "research_sublines/search/:search" => "research_sublines#search"
  get "programs/search/:search" => "programs#search"
  get "projects/search/:search" => "projects#search"
  get "results/search/:search" => "results#search"
  get "entries/search/:search" => "entries#search"
  get "users/search/:search" => "users#search"

  get "bydepartment" => "pages#bydepartment"

  match "/users/:id/all" => "users#show"

  get "timeline" => "pages#timeline", :as => "timeline"

  get "departments/show"

  get "departments/index"

  get "help" => "pages#help", :as => "help"

  get "about" => "pages#about", :as => "about"

  get "explore" => "pages#explore", :as => "explore"

  get "myaccount" => 'users#myaccount', :as => "myaccount"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get "signup" => "users#new", :as => "signup"

  resources :password_resets

  resources :users  do
    member do
      get :activate
    end
  end
  resources :sessions
  resources :entries
  resources :research_lines
  resources :research_sublines
  resources :knowledge_areas
  resources :departments
  resources :programs do
    resources :indicators
  end
  resources :projects
  resources :results
  resources :research_groups

  get "myentries" => "entries#myentries", :as => "myentries"

  get "myprograms" => "programs#myprograms", :as => "myprograms"
  get "myprojects" => "projects#myprojects", :as => "myprojects"
  get "myresults" => "results#myresults", :as => "myresults"
  get "mygroups" => "research_groups#mygroups", :as => "mygroups"

  root :to => 'pages#home'

end

app/models/program.rb
# encoding: utf-8
class Program < ActiveRecord::Base
  self.per_page = 5
  has_and_belongs_to_many :research_sublines
  has_and_belongs_to_many :knowledge_areas
  belongs_to :research_group
  belongs_to :user
  has_many :projects
  has_many :entries
  has_many :results, :through => :projects
  belongs_to :program_type

  attr_accessible :title, :description, :published, :research_group_id, :program_type_id, :finished, :start_date, :end_date

  validates_presence_of :title
  validates_presence_of :program_type

  def knowledge_area_names=(names)
    knowledge_areas = Array.new
    for name in names
      knowledge_area = KnowledgeArea.find_by_name(name)
      unless knowledge_area.nil?
        knowledge_areas.push(knowledge_area)
      end
    end
    self.knowledge_areas = knowledge_areas
  end

  attr_reader :knowledge_area_names
  attr_accessible :knowledge_area_names

  attr_reader :research_subline_names
  attr_accessible :research_subline_names

  def research_subline_names=(names)
    research_sublines = Array.new
    knowledge_areas = Array.new
    for name in names
      research_subline = ResearchSubline.find_by_name(name)
      unless research_subline.nil?
        research_sublines.push(research_subline)
        unless research_subline.knowledge_area.nil?
          knowledge_areas.push(research_subline.knowledge_area)
        end
      end
    end
    self.research_sublines = research_sublines
    self.knowledge_areas = knowledge_areas
  end

  def owned_by?(owner)
    return false unless owner.is_a? User
    if self.user == owner
      true
    elsif !self.research_group.nil?
      self.research_group.users.include?(owner)
    else
      false
    end
  end

  def state
    unless start_date.nil? or end_date.nil?
      now = DateTime.now.to_date
      if finished #finished
        "finished"
      elsif start_date < now and end_date > now # in progress
        "in_progress"
      elsif now < start_date #  pending
        "pending"
      elsif now > end_date and !finished # expired
        "expired"
      else
        4 # unknown
      end
    else
      4
    end
  end


  attr_reader :duration_years
  attr_accessible :duration_years

  def duration_years=(string)
    unless string.blank?
      unless self.duration.nil? or self.duration.blank? or self.duration[/\d+\s+(months|month|meses|mes)/].nil?
        self.duration = self.duration[/\d+\s+(months|month|meses|mes)/] + " " + string
      else
        self.duration = string
      end
    end
  end

  def duration_years
    duration[/\d+\s+(years|year|años|año|anos|ano|anios|anio)/]
  end

  attr_reader :duration_months
  attr_accessible :duration_months

  def duration_months=(string)
    unless string.blank?
      unless self.duration.nil? or self.duration.blank? or self.duration[/\d+\s+(years|year|años|año|anos|ano|anios|anio)/].nil?
        self.duration = self.duration[/\d+\s+(years|year|años|año|anos|ano|anios|anio)/] + " " + string
      else
        self.duration = string
      end
    end
  end

  def duration_months
    duration[/\d+\s+(months|month|meses|mes)/]
  end


  attr_reader :duration
  attr_accessible :duration

  def duration=(string)
    years_string = string[/\d+\s+(years|year|años|año|anos|ano|anios|anio)/]
    months_string = string[/\d+\s+(months|month|meses|mes)/]
    days_string = string[/\d+\s+(days|day|días|día|dias|dia)/]

    unless years_string.blank? or years_string[/\d+/].nil?
      years = Integer(years_string[/\d+/])
    else
      years = 0
    end
    unless months_string.blank? or months_string[/\d+/].nil?
      months = Integer(months_string[/\d+/])
    else
      months = 0
    end
    unless days_string.blank? or days_string[/\d+/].nil?
      days = Integer(days_string[/\d+/])
    else
      days = 0
    end

    unless self.start_date.nil? or self.start_date.blank?
      self.end_date = start_date + years.years + months.months + days.days
    end
  end

  def duration
    unless self.start_date.nil? or self.end_date.nil?
      duration = self.end_date - self.start_date
      months = Integer(duration)/30
      output = ChronicDuration::output(months.months, :format => :long)
      output = output.gsub('year', 'año')
      output = output.gsub('months', 'meses')
      output = output.gsub('month', 'mes')
      output = output.gsub('day', 'día')
      output
    else
      ''
    end
  end


  def self.search(query)
    where do
      (title =~ "%#{query}%") | (description =~ "%#{query}%")
    end
  end
end

app/models/program_type.rb
class ProgramType < ActiveRecord::Base
  has_many :programs
end

app/controllers/programs_controller.rb
# encoding: utf-8
class ProgramsController < ApplicationController
  before_filter :require_login, :only => [:new, :edit, :create, :update, :destroy, :myprograms]
  def is_owner?
    program = Program.find(params[:id])
    unless current_user.nil?
      if !program.owned_by?(current_user)
        unless program.published
          redirect_to root_path
        end
      end
    else
      unless program.published
        redirect_to root_path, :notice => t('application.please_sign_in')
      end
    end
  end
  before_filter :is_owner?, :only => [:show]

  def myprograms
    @user_programs = current_user.programs
    @groups_programs = current_user.groups_programs
    @programs = @user_programs + @groups_programs
    @programs.sort_by(&:created_at)
    @programs = @programs.paginate(:page => params[:page])

    if @programs.empty?
      respond_to do |format|
        format.html { render :template => 'pages/myempty', :locals => { :model => Program } }
      end
    else
      respond_to do |format|
        format.html { render :template => 'programs/index' }
        format.json { render json: @programs }
        format.js { render :template => 'programs/index' }
      end
    end
  end

  def program_type
    @type = ProgramType.find(params[:id])
    @programs = @type.programs.where(:published => true).paginate(:page => params[:page])
    respond_to do |format|
      format.html { render :template => 'programs/index' }
    end
  end


  def index
    @programs = Program.where(:published => true).paginate(:page => params[:page])

    if @programs.empty?
      respond_to do |format|
        format.html { render :template => 'pages/empty' }
      end
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @programs }
        format.js
      end
    end
  end

  def show
    @program = Program.find(params[:id])

    respond_to do |format|
      format.html # timeline.html.erb
      format.json { render json: @program }
    end
  end

  def new
    @program = Program.new
    @groups = current_user.research_groups
    @types = ProgramType.all


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @program }
    end
  end

  def edit
    @program = current_user.programs.find(params[:id])
    @program = current_user.programs.find(params[:id])
    if @program.nil?
      @program.current_user.groups_programs.find(params[:id])
    end
    @groups = current_user.research_groups
    @types = ProgramType.all
  end

  def create
    @program = current_user.programs.new(params[:program])

    respond_to do |format|
      if @program.save
        session[:mixpanel] = "mixpanel.track('crear programa');"
        format.html { redirect_to @program, notice: t('program.create') }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @program = Program.find(params[:id])

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to @program, notice: t('program.update') }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :ok }
    end
  end

  def search
    @programs = Program.search(params[:search]).paginate(:page => params[:page])
    @collection = @programs
    respond_to do |format|
      format.html { render :template => 'pages/search' }
      format.js { render :template => 'pages/search' }
    end
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= tinymce_assets %>
<%= simple_nested_form_for @program, :validate => true, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @program.errors.any? %>
    <div class="alert">
      <button class="close" data-dismiss="alert">x</button>
      <strong><%= t('application.warning') %></strong> <%= t('entry.could_not_create', :count => @program.errors.count) %>
    </div>
  <% end %>

  <%= f.input :title, :input_html => { :class => 'span7' } %>
  <%= f.input :start_date, :as => :string, :input_html => { :class => 'span7' } %>

  <div class="control-group string optional">
    <%= f.label :duration %>
    <div class="controls">
      <%= f.input_field :duration_years, :collection => years_collection, :prompt => t('application.years') %>
      <%= f.input_field :duration_months, :collection => months_collection, :prompt => t('application.months') %>
    </div>
  </div>
  <%= f.association :program_type, :collection => @types ,:input_html => { :class => 'span7' } %>
  <%= f.association :research_group, :collection => @groups , :input_html => { :class => 'span7' } %>

  <div class="control-group">
    <label class="control-label"><%= t('entry.research_sublines') %></label>
    <div class="controls">
      <%= content_tag :ul, :class => "span7", :id => "research-sublines", data: {autocomplete_source: ResearchSubline.order(:name).map(&:name)}  do %>
        <% for research_subline in @program.research_sublines %>
          <li><%= research_subline.name %></li>
        <% end %>
      <% end %>
    </div>
  </div>



  <%= f.input :published %>
  <%= f.input :finished %>

  <%= f.input :description, :input_html => { :class => 'tinymce span7' } %>
  <%= tinymce %>

  <div class="form-actions">
    <div class="pull-right">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  entries_path, :class => 'btn' %>
    </div>
  </div>
<% end %>

app/views/programs/_program.html.erb
<%= content_tag_for(:li, program, :class => "entry") do %>
  <div class="row">
    <div class="span2">
      <% if program.owned_by? current_user %>
        <span class="label label-<%= program.published ? 'info' : 'warning' %>"><%= program.published ? t('entry.published') : t('entry.not_published') %></span>
      <% end %>
      <%= link_to program_path(program), :class => 'thumbnail' do %>
          <img src="http://www.placehold.it/160x155/EFEFEF/AAAAAA&amp;text=Programa">
      <% end %>
    </div>
    <div class="span6">
      <%= link_to program_path(program) do %>
        <h2><%= program.title %></h2>
      <% end %>
      <% if program.owned_by? current_user %>
        <div class="entry-actions pull-right">
          <%= link_to edit_program_path(program), :class => 'btn btn-mini btn-success' do %>
            <i class="icon-pencil icon-white"></i> <%= t('.edit', :default => t("helpers.links.edit")) %>
          <% end %>
          <%= link_to program_path(program),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' do %>
            <i class="icon-remove icon-white"></i> <%= t('.destroy', :default => t("helpers.links.destroy")) %>
          <% end %>
        </div>
      <% end %>
      <% unless program.research_group.nil? %>
        <h3><%= link_to program.research_group.name, research_group_path(program.research_group) %></h3>
      <% else %>
        <h3><%= link_to program.user.header_name, user_path(program.user) %></h3>
      <% end %>

      <% unless program.description.blank? %>
        <%= truncate_html strip_tags(program.description).gsub("&nbsp;", ""), :length => 250 %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/programs/edit.html.erb
<div class="span9" id="program-form">
  <div class="well">
  <%- model_class = @program.class -%>
  <div class="page-header">
    <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                     :default => "Editar #{model_class.model_name.human}") %></h1>
  </div>
  <%= render :partial => 'form' %>
  </div>
</div>

app/views/programs/index.html.erb
<%- model_class = Program.new.class -%>
<div class="span8">
  <div class="well">
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human(:count => @programs.count )%></h1>
  </div>
  <ul class="thumbnails entries">
    <%= render @programs %>
  </ul>
  <div class="pull-right">
    <%= will_paginate @programs, :renderer => BootstrapPagination::Rails %>
  </div>
  </div>
</div>
<div class="span4">
  <%= render "entries/sidebar" %>
  <%= render "pages/sidebar" %>
</div>

app/views/programs/index.js.erb
$('.entries').append('<%= j render(@programs) %>');
<% if @programs.next_page %>
$('.pagination').replaceWith('<%= j will_paginate(@programs, :renderer => BootstrapPagination::Rails) %>');
<% else %>
$('.pagination').remove();
<% end %>

app/views/programs/new.html.erb
<div class="span9" id="program-form">
  <div class="well">
  <%- model_class = @program.class -%>
  <div class="page-header">
    <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                     :default => "Nuevo #{model_class.model_name.human}") %></h1>
  </div>
  <%= render :partial => 'form' %>
  </div>
</div>

app/views/programs/show.html.erb
<%- model_class = @program.class -%>
<div class="span8 entry">
  <div class="well">
  <div class="page-header">
    <h1><%= @program.title %></h1>
    <div class="entry-actions">
      <%= link_to just_created_or_updated ? myprograms_path : :back, :class => 'btn btn-mini' do %>
        <i class="icon-white icon-arrow-left"></i> <%= t('.back', :default => t("helpers.links.back")) %>
      <% end %>
      <% if @program.owned_by? current_user %>
        <%= link_to edit_program_path(@program), :class => 'btn btn-mini btn-success' do %>
          <i class="icon-pencil icon-white"></i> <%= t('.edit', :default => t("helpers.links.edit")) %>
        <% end %>
        <%= link_to program_path(@program),
                    :method => 'delete',
                    :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                    :class => 'btn btn-danger btn-mini' do %>
          <i class="icon-remove icon-white"></i> <%= t('.destroy', :default => t("helpers.links.destroy")) %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="page-header">

    <% unless @program.research_group.nil? %>
      <div>
        <h3 class="author"><%= t("application.done_by") %>:</h3>
        <h4 class="author"><%= link_to @program.research_group.name, url_for(@program.research_group) %></h4>
      </div>
    <% else%>
      <div>
        <h3 class="author"><%= t("application.done_by") %>:</h3>
        <h4 class="author"><%= link_to @program.user.name, url_for(@program.user) %></h4>
      </div>
    <% end %>
    <% unless @program.program_type.nil? %>
      <div>
        <h3 class="author"><%= t("activerecord.models.program_type.one") %>:</h3>
        <h4 class="author"><%= link_to @program.program_type.name, url_for(:id => @program.program_type.id, :action => "program_type") %></h4>
      </div>
    <% end %>
    <% unless @program.start_date.nil? %>
      <div>
        <h3 class="author"><%= t('activerecord.attributes.project.start_date') %>:</h3>
        <h4 class="author"><%= @program.start_date %></h4>
      </div>
    <% end %>
    <% unless @program.duration.blank? %>
      <div>
        <h3 class="author"><%= t('activerecord.attributes.project.duration') %>:</h3>
        <h4 class="author"><%= @program.duration %></h4>
      </div>
    <% end %>
    <% unless @program.state == 4 %>
      <div>
        <h3 class="author"><%= t('activerecord.attributes.program.state') %>:</h3>
        <h4 class="author"><%= t('program.' + @program.state) %></h4>
      </div>
    <% end %>
    <% unless @program.knowledge_areas.empty? %>
      <h3><%= t("application.departments_part") %>:</h3>
      <h4>
        <ul>
          <% for knowledge_area in @program.knowledge_areas %>
            <li>
            <%= link_to knowledge_area.department.name, department_path(knowledge_area.department.id) %> <small>(<%= link_to knowledge_area.name, knowledge_area_path(knowledge_area.id) %>)</small>
            </li>
          <% end %>
        </ul>
      </h4>
    <% end %>

    <% unless @program.research_sublines.empty? %>
      <h3><%= t("application.research_lines_inc") %>:</h3>
      <h4>
        <ul>
          <% for research_subline in @program.research_sublines %>
            <li>
              <%= link_to research_subline.research_line.name, research_line_path(research_subline.research_line) %> <small>(<%= link_to research_subline.name, url_for(research_subline) %>)</small>
            </li>
          <% end %>
        </ul>
      </h4>
    <% end %>

    <% unless @program.description.blank?  %>
    <h3><%= t "application.description" %>: </h3>
  </div>



  <div class="content">

    <%= @program.description.html_safe %>
    <% end %>
  </div>

  <hr>

  <% unless @program.projects.empty? %>
    <h3><%= t("application.projects_comp") %>:</h3>
    <h4>
      <ul>
        <% if !current_user.nil? and @program.owned_by?(current_user) %>
          <% for project in @program.projects %>
            <li>
              <%= link_to project.title + " (" + t("program."+project.state) + ")", project_path(project.id) %>
            </li>
          <% end %>
        <% else %>
          <% for project in @program.projects.where(:published  => true) %>
            <li>
              <%= link_to project.title + " (" + t("program."+project.state) + ")", project_path(project.id) %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </h4>
    <hr>
  <% end %>
  </div>
</div>

<div class="span4">
  <%= render 'entries/sidebar' %>

</div>


<div class="span8">
  <div class="well">
  <div id="disqus_thread"></div>
  <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'tesisespe'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
 </div>
</div>