config/routes.rb
VirtusKnowledge::Application.routes.draw do

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  get "indicators/show"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/research_groups/:id/programs" => "research_groups#programs"
  match "/research_groups/:id/projects" => "research_groups#projects"
  match "/research_groups/:id/results" => "research_groups#results"

  match "/research_lines/:id/programs" => "research_lines#programs"
  match "/research_lines/:id/projects" => "research_lines#projects"
  match "/research_lines/:id/results" => "research_lines#results"
  match "/research_lines/:id/entries" => "research_lines#entries"
  match "/research_lines/:id/research_sublines" => "research_lines#research_sublines"

  match "/research_sublines/:id/programs" => "research_sublines#programs"
  match "/research_sublines/:id/projects" => "research_sublines#projects"
  match "/research_sublines/:id/results" => "research_sublines#results"
  match "/research_sublines/:id/entries" => "research_sublines#entries"

  match "/knowledge_areas/:id/programs" => "knowledge_areas#programs"
  match "/knowledge_areas/:id/projects" => "knowledge_areas#projects"
  match "/knowledge_areas/:id/results" => "knowledge_areas#results"
  match "/knowledge_areas/:id/entries" => "knowledge_areas#entries"

  match "/departments/:id/knowledge_areas" => "departments#knowledge_areas"
  match "/departments/:id/programs" => "departments#programs"
  match "/departments/:id/projects" => "departments#projects"
  match "/departments/:id/results" => "departments#results"
  match "/departments/:id/entries" => "departments#entries"

  match "/users/:id/programs" => "users#programs"
  match "/users/:id/projects" => "users#projects"
  match "/users/:id/results" => "users#results"
  match "/users/:id/entries" => "users#entries"
  match "/users/:id/groups_programs" => "users#groups_programs"
  match "/users/:id/groups_projects" => "users#groups_projects"
  match "/my_groups_programs" => "users#my_groups_programs", :as => "my_groups_programs"
  match "/my_groups_projects" => "users#my_groups_projects", :as => "my_groups_projects"

  match "/programs/type/:id" => "programs#program_type"

  match "/research_groups/:object_id/type/:type_id" => "research_groups#program_type"
  match "/departments/:object_id/type/:type_id" => "departments#program_type"
  match "/users/:object_id/type/:type_id" => "users#program_type"

  match "search/:search" => "pages#search"
  match "search/" => "pages#search", :as => "search_general"

  get "departments/search/:search" => "departments#search"
  get "knowledge_areas/search/:search" => "knowledge_areas#search"
  get "research_lines/search/:search" => "research_lines#search"
  get "research_sublines/search/:search" => "research_sublines#search"
  get "programs/search/:search" => "programs#search"
  get "projects/search/:search" => "projects#search"
  get "results/search/:search" => "results#search"
  get "entries/search/:search" => "entries#search"
  get "users/search/:search" => "users#search"

  get "bydepartment" => "pages#bydepartment"

  match "/users/:id/all" => "users#show"

  get "timeline" => "pages#timeline", :as => "timeline"

  get "departments/show"

  get "departments/index"

  get "help" => "pages#help", :as => "help"

  get "about" => "pages#about", :as => "about"

  get "explore" => "pages#explore", :as => "explore"

  get "myaccount" => 'users#myaccount', :as => "myaccount"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get "signup" => "users#new", :as => "signup"

  resources :password_resets

  resources :users  do
    member do
      get :activate
    end
  end
  resources :sessions
  resources :entries
  resources :research_lines
  resources :research_sublines
  resources :knowledge_areas
  resources :departments
  resources :programs do
    resources :indicators
  end
  resources :projects
  resources :results
  resources :research_groups

  get "myentries" => "entries#myentries", :as => "myentries"

  get "myprograms" => "programs#myprograms", :as => "myprograms"
  get "myprojects" => "projects#myprojects", :as => "myprojects"
  get "myresults" => "results#myresults", :as => "myresults"
  get "mygroups" => "research_groups#mygroups", :as => "mygroups"

  root :to => 'pages#home'

end

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36573344-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_inspectlet.html.erb
<!-- Begin Inspectlet Embed Code -->
<script type="text/javascript" id="inspectletjs">
  var __insp = __insp || [];
  __insp.push(['wid', 3052049585]);
  (function() {
    function __ldinsp(){var insp = document.createElement('script'); insp.type = 'text/javascript'; insp.async = true; insp.id = "inspsync"; insp.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://www.inspectlet.com/inspect/3052049585.js'; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(insp, x); }
    if (window.attachEvent){
      window.attachEvent('onload', __ldinsp);
    }else{
      window.addEventListener('load', __ldinsp, false);
    }
  })();
</script>
<!-- End Inspectlet Embed Code -->

app/views/layouts/_mixpanel.html.erb
<!-- start Mixpanel --><script type="text/javascript">(function(c,a){window.mixpanel=a;var b,d,h,e;b=c.createElement("script");b.type="text/javascript";b.async=!0;b.src=("https:"===c.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.1.min.js';d=c.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d);a._i=[];a.init=function(b,c,f){function d(a,b){var c=b.split(".");2==c.length&&(a=a[c[0]],b=c[1]);a[b]=function(){a.push([b].concat(Array.prototype.slice.call(arguments,0)))}}var g=a;"undefined"!==typeof f?
    g=a[f]=[]:f="mixpanel";g.people=g.people||[];h="disable track track_pageview track_links track_forms register register_once unregister identify name_tag set_config people.identify people.set people.increment".split(" ");for(e=0;e<h.length;e++)d(g,h[e]);a._i.push([b,c,f])};a.__SV=1.1})(document,window.mixpanel||[]);
mixpanel.init("068db0eb122caa82d2238786c948b85b");</script><!-- end Mixpanel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)  %>Sistema de Difusión de Gestión de Conocimiento ESPE</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render "layouts/google_analytics" %>
  <%= render "layouts/mixpanel" %>
  <%= render "layouts/inspectlet" %>
  <script type="text/javascript">
    <%= raw @mixpanel %>
  </script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= nav_bar :fixed => "top", :brand => "ESPE", :responsive => true do %>
    <h2>Sistema de Difusión de la Gestión del Conocimiento de la ESPE</h2>
    <h3>Vicerrectorado de Investigación y Vinculación con la Colectividad</h3>
		<%= menu_group do %>
			<%= menu_item '<i class="icon-home icon-white"></i> '.html_safe + t("application.home"), root_path %>
			<%= menu_item '<i class="icon-globe icon-white"></i> '.html_safe + t("application.explore"), explore_path %>
			<%= menu_item '<i class="icon-question-sign icon-white"></i> '.html_safe + t('application.help'), help_path %>
			<%= menu_item '<i class="icon-info-sign icon-white"></i> '.html_safe + t('application.about'), about_path %>
		<% end %>
		<%= menu_group :pull => :right do %>
      <%= form_tag search_general_path, :class => "form-search navbar-search", method: :get do %>
        <%= text_field_tag :search, params[:search], :placeholder => t("application.search") %>
      <% end %>
    <% end %>
    <%= menu_group :pull => :right do %>
      <% if current_user %>
        <%= drop_down '<i class="icon-user icon-white"></i> '.html_safe + current_user.header_name do %>
          <div class="group-container">
          <div class="group group-left">
          <li class="nav-header"><%= t 'activerecord.models.program.other' %></li>
          <%= menu_item '<i class="icon-folder-open icon-white"></i> '.html_safe + t('user.myprograms'), myprograms_path %>
          <%= menu_item '<i class="icon-folder-open icon-white"></i> '.html_safe + t('user.my_groups_programs'), my_groups_programs_path %>
          <%= menu_item '<i class="icon-plus icon-white"></i> '.html_safe + t('user.create_program'), new_program_path %>
          <%= drop_down_divider %>
          <li class="nav-header"><%= t 'activerecord.models.project.other' %></li>
          <%= menu_item '<i class="icon-book icon-white"></i> '.html_safe + t('user.myprojects'), myprojects_path %>
            <%= menu_item '<i class="icon-book icon-white"></i> '.html_safe + t('user.my_groups_projects'), my_groups_projects_path %>
          <%= menu_item '<i class="icon-plus icon-white"></i> '.html_safe + t('user.create_project'), new_project_path %>
          <%= drop_down_divider %>
          <li class="nav-header"><%= t 'activerecord.models.result.other' %></li>
          <%= menu_item '<i class="icon-bar-chart icon-white"></i> '.html_safe + t('user.myresults'), myresults_path %>
          <%= menu_item '<i class="icon-plus icon-white"></i> '.html_safe + t('user.create_result'), new_result_path %>
          <%= drop_down_divider %>
          </div>
          <div class="group">
          <li class="nav-header"><%= t 'activerecord.models.entry.other' %></li>
          <%= menu_item '<i class="icon-copy icon-white"></i> '.html_safe + t('user.myentries'), myentries_path %>
          <%= menu_item '<i class="icon-plus icon-white"></i> '.html_safe + t('user.create_entry'), new_entry_path %>
            <%= drop_down_divider %>
          <li class="nav-header"><%= t 'activerecord.models.research_group.other' %></li>
          <%= menu_item '<i class="icon-group icon-white"></i> '.html_safe + t('user.myresearch_groups'), mygroups_path %>
          <%= menu_item '<i class="icon-plus icon-white"></i> '.html_safe + t('user.create_research_group'), new_research_group_path %>
          <%= drop_down_divider %>
          <%= menu_item '<i class="icon-edit icon-white"></i> '.html_safe + t('user.my_account'), myaccount_path %>
          <%= menu_item '<i class="icon-signout icon-white"></i> '.html_safe + t('user.signout'), logout_path %>
          </div>
          </div>
        <% end %>
      <% else %>
        <%= drop_down '<i class="icon-signin icon-white"></i> '.html_safe + t("application.signin") do %>
          <%= render :partial => 'sessions/form_small' %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

	<div class="container">
		<% flash.each do |name, msg| %>
	      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
	        <a class="close" data-dismiss="alert">×</a>
	        <%= msg %>
	      </div>
	    <% end %>
		<div class="row main-content">
			<%= yield %>
		</div>
	</div>


	<div class="footer-container">
      <div class="footer-accent"></div>
      <footer class="container">
      
        <div class="row">
          <p class="pull-right"><a href="#">Arriba ↑</a></p>
        </div>
        <div class="row">
          <!--<div class="span10 offset1">-->
            <!--<div class="well">  -->
              <!--<ul>-->
               <!--<li>-->
                 <!--<div>-->
                  <!--<a href="#">-->
                   <!--<img src="custom/images/twitter.png" height="50" width="50" alt="Twitter">-->
                 <!--</a>-->
                 <!--</div>-->
               <!--</li>-->
               <!--<li>-->
                 <!--<div>-->
                  <!--<a href="#">-->
                   <!--<img src="custom/images/facebook.png" height="50" width="50" alt="Facebook">-->
                 <!--</a>-->
                 <!--</div>-->
               <!--</li>-->
               <!--<li>-->
                <!--<div>-->
                  <!--<a href="#">-->
                    <!--<img src="custom/images/google.png" height="50" width="50" alt="Google+">-->
                  <!--</a>-->
                <!--</div>-->
              <!--</li>-->
             <!--</ul>-->
            <!--</div>-->
          <!--</div>-->
        </div>
        <p>Copyright &copy; 2013 - Sistema de Difusión de la Gestión del Conocimiento de la ESPE</p>
      </footer>
    </div>

</body>
</html>